package ca.ubc.ctlt.copyalerts.alertsmodule;

import java.io.IOException;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

public class AlertsModuleRouter extends HttpServlet
{
	/** Autogenerated Serial */
	private static final long serialVersionUID = 3333382930488544973L;

	public void doGet(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
	{
		// pass on request to appropriate view
		RequestDispatcher dispatcher = request.getRequestDispatcher("/WEB-INF/view/alertsmodule/view.jsp");
		if (dispatcher != null) 
		{
			dispatcher.forward(request, response);
		}
	}
	
}
