package ca.ubc.ctlt.copyalerts.alertsmodule;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

public class AlertsModuleAPI extends HttpServlet
{
	/** Autogenerated serial */
	private static final long serialVersionUID = 7933482274005364346L;

	public void doGet(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException
	{
		String path = request.getPathInfo();
		System.out.println("Path Info: " + path);
		response.setContentType("application/json");
		response.setCharacterEncoding("UTF-8");
		if (path.equals("/files"))
		{ // returns a json map of all the schedule configuration values
			response.getWriter().write("{\"Test\":\"123\"}");
		}
		else
		{
			response.sendError(404);
		}
	}
}
