package ca.ubc.ctlt.copyalerts.scheduler;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;

import blackboard.persist.PersistenceRuntimeException;
import org.quartz.SchedulerException;
import blackboard.platform.vxi.service.VirtualSystemException;
import ca.ubc.ctlt.copyalerts.configuration.HostResolver;
import ca.ubc.ctlt.copyalerts.db.HostsTable;
import ca.ubc.ctlt.copyalerts.db.InaccessibleDbException;

public class SchedulerStarter extends HttpServlet
{
	/** Autogenerated serial */
	private static final long serialVersionUID = 1738736327585377900L;

	/** 
	 * Convenience method that can be overridden to do stuff when this servlet gets placed into service.
	 */
	@Override
	public void init() throws ServletException
	{
		try
		{
			HostsTable hostTable = new HostsTable();
			// store this host into the hosts table
			String hostname = HostResolver.getHostname();
			if (!hostTable.hasHost(hostname))
			{
				hostTable.addHost(hostname);
			}
		} catch (VirtualSystemException e)
		{
			throw new ServletException(e);
		}

		try
		{
			SchedulerManager.getInstance().updateScheduler();
		} catch (SchedulerException e)
		{
			throw new ServletException(e);
		}
	}

	/* (non-Javadoc)
	 * @see javax.servlet.GenericServlet#destroy()
	 */
	@Override
	public void destroy()
	{
		SchedulerManager.getInstance().stop();
	}
	
}
